version: '3.9'
services:
  cdn:
    build: cdn_emulator
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    depends_on:
      - couchdb

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - couchdb
    extra_hosts:
      - "host.docker.internal:host-gateway"

  couchdb:
    image: couchdb:3.3.3
    restart: always
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    volumes:
      - couchdb:/opt/couchdb/data

volumes:
    couchdb: